### ISSUE TITLE
Secure text entry TextInput is readable

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#423] opened 2020-05-27 10:56 UTC
### Environment

info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.43 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/.volta/tools/image/node/14.2.0/6.14.4/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 6.14.4 - ~/.volta/tools/image/node/14.2.0/6.14.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to Reproduce
Use a TextInput with secureTextEntry flag set to true

### Expected Behavior

Text is obfuscated

### Actual Behavior

Text is visible and after reload background is red.

**Comment by Simek** [comment] 2020-05-27 16:43
From the comment in the code it looks like `secureTextEntry` property is not implemented yet:
* https://github.com/microsoft/react-native-macos/blob/master/Libraries/Text/TextInput/RCTBaseTextInputView.m#L337

**Comment by tom-un** [comment] 2020-06-09 22:32
Correct: it has not been implemented for mac.  It would require projecting a `NSSecureTextField` instead of a `NSTextField`.

**Comment by elcssmouhsine** [comment] 2020-07-12 07:07
any plans on fixing this

**Comment by tom-un** [comment] 2020-07-13 22:42
I'm afraid it's not a priority for us right now.   But we would welcome Pull Requests adding this feature.

**Comment by tom-un** [comment] 2020-09-22 11:04
Some more details on a possible implementation:
In `RCTSinglelineTextInputView.m` there is an ivar named `_backedTextInputView`.   It is initialized to be a `RCTUITextField` which is a subclass of `UITextField` on iOS or `NSTextField` on macOS.    On iOS, `setSecureTextEntry:YES` can simply be called on the `UITextField` to place it in secure text entry mode.   On macOS, there is no such property.   Instead the entire `NSTextField` has to be replaced with a `NSSecureTextField` which is a subclass of `NSTextField`.   I believe that what will have to happen is that a `RCTSecureTextField` class will have to be defined which subclasses `NSSecureTextField` and conforms to the `RCTBackedTextInputViewProtocol` protocol (basically a duplicate of `RCTUITextField` but with a different base class).   Then in `RCTSinglelineTextInputView` when in secure text mode, the `_backedTextInputView` will have to be replaced by a new instance of `RCTSecureTextField`.    The challenge would be figuring out a way to *not* duplicate so much code between `RCTUITextField.m` and `RCTSecureTextField` which should be identical except for their base class and the base class of `RCTUITextFieldCell` (`NSTextFieldCell` or `NSSecureTextFieldCell`).   In lieu of C++ style templates in ObjC, perhaps the common implementation code could be `#included` into the two classes implementation files.

**Closed** 2020-09-28 09:40 UTC
Labels: Partner: Facebook
