### ISSUE TITLE
Layout bug when resizing main window 

### ISSUE THREAD

**Issue by mgcrea** [microsoft/react-native-macos#322] opened 2020-04-26 14:22 UTC
I've been playing a bit with react-native-macos and I encountered a strange bug when resizing the main window, not sure where exactly the issue is. Here is the bug:

Looks like it is somehow triggered by long clipping text (tried available clipping options with no luck) and especially when you don't release the mousedown.

![Screen Recording 2020-04-26 at 16 19 57](https://user-images.githubusercontent.com/108273/80310245-f5d12980-87d9-11ea-8649-1ffc9d97a7a0.gif)

Has anyone encountered this?

```
▶ cat package.json| jq .dependencies | grep react
  "react": "16.13.1",
  "react-native": "0.62.2",
  "react-native-macos": "^0.60.0-microsoft.76",
```

**Comment by mayank-budhiraja** [comment] 2020-06-02 13:14
@mgcrea can you help me reproduce to issue?

**Comment by TheSavior** [comment] 2020-06-02 16:39
Ah, I may have created a duplicate of this here: https://github.com/microsoft/react-native-macos/issues/422

**Comment by mayank-budhiraja** [comment] 2020-06-02 17:07
@TheSavior Yes! 
I tested with the sample project. It's a duplicate. Do you know how to resolve it?

@

**Comment by TheSavior** [comment] 2020-06-02 17:32
I closed the duplicate. 

I haven't investigated this issue beyond the report

**Closed** 2020-06-29 21:33 UTC
Labels: Partner: Facebook
