### ISSUE TITLE
Not able to remove blue frame for TextInput when in focus

### ISSUE THREAD

**Issue by mayyaab** [microsoft/react-native-macos#821] opened 2021-08-26 18:47 UTC
### Environment

1. `react-native -v`: 0.64.1
3. `npm ls react-native-macos`: 0.63.0-0
4. `node -v`: v14.17.3
5. `npm -v`: 6.14.13
6. `yarn --version`: 1.22.10
7. `xcodebuild -version`: Xcode 12.5.1
Build version 12E507

### Issue

Can not remove the blue border of TextInput when the element in focus.

<img width="511" alt="Screen Shot 2021-08-26 at 11 46 01 AM" src="https://user-images.githubusercontent.com/41024017/131018910-335de2a6-5359-469c-90e2-b8fab6b60c0e.png">

```
<TextInput
          style={style.input}
          placeholder="Enter email"
          placeholderTextColor={colors.paragraphLight}
          onChangeText={(text) => setUserName(text)}
          defaultValue={userName}
        />


input: {
    marginTop: 16,
    height: 40,
    width: 400,
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    borderColor: colors.innerBorder,
    color: colors.plainBlack,
  },
```

**Comment by chrisglein** [comment] 2021-09-09 17:47
That `borderColor` doesn't map to the `TextInput`'s focus border. However there isn't a way to turn that off currently (see #795)

**Comment by chrisglein** [comment] 2021-09-09 17:48
Duplicate of #795

**Closed** 2021-09-09 17:48 UTC
Labels: duplicate, Area: TextInput
