### ISSUE TITLE
Cannot install React Native for macOS

### ISSUE THREAD

**Issue by maphongba008** [microsoft/react-native-macos#1805] opened 2023-04-29 17:12 UTC
### Environment

```markdown
Can't run `npx react-native init NewProject --template react-native@^0.71.0`
```

### Steps to reproduce the bug

Follow steps 1 on: https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

Run: npx react-native init NewProject --template react-native@^0.71.0

Got error: zsh: no matches found: react-native@^0.71.0

I can create new RN project with "npx react-native init -- <projectName>", but add `--template react-native@^0.71.0` makes it do not work

### Expected Behavior

It will create a new RN macos project successfully 

### Actual Behavior

Got error: zsh: no matches found: react-native@^0.71.0

**Comment by Saadnajmi** [comment] 2023-04-29 17:45
Duplicate of #1798 but an issue we're aware of, thanks for the report!

**Closed** 2023-04-29 17:45 UTC
Labels: bug, Needs: Triage :mag:
